# docker run -d \
# --name registration-container \
# -p 5001:5001 \
# --env-file .env \
# danan22/registration-service:v1

services:
  registration-service:
    image: danan22/registration-service:v1
    container_name: registration-container
    ports:
      - "5001:5001"
    env_file:
      - .env
